### ISSUE TITLE
Different Reference

### ISSUE THREAD

**Issue by denise0593** [15274972986/CORONATATOR#1]
Hi!
How can I do if I need to use a different reference from the one you have?
I've tried to create the folder and the gb file but the software still gives me an error: "[main_samview] region "nCoV-2019.reference" specifies an invalid region or unknown reference. Continue anyway.
Failed to read from standard input: unknown file type
Failed to read from standard input: unknown file type
Failed to read from standard input: unknown file type"
Thanks

**Comment by 15274972986** [comment]
This tool is not so flexible like that, as every reference has its own LTRS position (though the position varies little between different reference from same species), we have recorded that in "species_LTRS.tsv". A new reference from same species is not allowed to be exist simultaneously with the original one, if you want to do that, please replace the original one. 
Feel free to ask more questions. ^_^

**Comment by 15274972986** [comment]
remember you need also change LTRS position in "species_LTRS.tsv" if you have changed reference.

**Comment by denise0593** [comment]
Thank you so much! 
I have another question for you: How do you determine the LTRS position to give as input in "species_LTRS.tsv"?

Secondly, I want to suggest you to change "samtools mpileup" with "bcftools mpileup" in the preproc.sh 
```
samtools view -h $BAM $VHEADER | samtools mpileup -t SP -t DP -gf $REF - | $BCFTOOLS call -vcO z  - | $BCFTOOLS filter -O v -e 'QUAL<50' - | $BCFTOOLS view -g hom -Oz -o out.filter.vcf.gz

samtools view -h $BAM $VHEADER | $BCFTOOLS mpileup -t SP -t DP -f $REF - | $BCFTOOLS call --ploidy 1 -vcO z - | $BCFTOOLS filter -O v -e 'QUAL<50' - | $BCFTOOLS view -g hom -Oz -o out.filter.vcf.gz

```
as samtools gives some errors.

**Comment by denise0593** [comment]
May I ask you also how best to interpret the different output files? 
Thank you so much.

**Comment by 15274972986** [comment]
thank you for your suggestion, the ‘mpileup‘ command on our server give us warnings as 'mpileup' is due to be deprecated (though it workded fine during our project), we will modify it later.
for the first question about LTRS, different species may have different LTRS, for SARS-CoV-2, it is believed to be  'AAACGAAC', so you need to search the sequence from 5' to 3' on viral genome (use the central site of that sequence in genome), and change the number behind SARS2 in species_LTRS.tsv

**Comment by denise0593** [comment]
Thank you so much!
May I ask you to better explain the output files? 
I'm not sure about my interpretation of the results.
Thank you!

**Comment by 15274972986** [comment]
sorry, I was writting '[README.md](https://github.com/15274972986/CORONATATOR/tree/master#readme)' when you have made that reply, so, I updated 'README.md', you can refer to that file for interpretation of outputs.

**Comment by denise0593** [comment]
Thank a lot!
